apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: consumer-metrics
  namespace: monitoring
  labels:
    app: strimzi
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: consumer
  namespaceSelector:
    matchNames:
      - strimzi
  podMetricsEndpoints:
    - port: metrics
