apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
  namespace: strimzi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
      - name: consumer
        image: consumer:dev
        imagePullPolicy: Never
        ports:
        - containerPort: 9000
          name: metrics
        env:
          - name: KAFKA_CLUSTER_URL
            value: my-cluster-kafka-bootstrap.strimzi.svc:9092
          - name: KAFKA_TOPIC
            value: weather-events
          - name: KAFKA_CONSUMER_GROUP_ID
            value: weather_events_consumer_1