apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer
  namespace: strimzi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
      - name: producer
        image: producer:dev
        imagePullPolicy: Never
        ports:
        - containerPort: 9000
          name: metrics
        env:
          - name: KAFKA_CLUSTER_URL
            value: my-cluster-kafka-bootstrap.strimzi.svc:9092
          - name: KAFKA_TOPIC
            value: weather-events